sudo: false
cache: pip
language: python
python:
    - 3.6

install:
  - pip install pipenv
  - make dev-install
  - pip install codecov

script:
  - make lint
  - make test

branches:
  only:
    - master

after_success:
  - codecov